title: Humax 2Tune Hacking (Humhax)
description: Documenting the Humax 2Tune PVR.
theme: just-the-docs

url: https://humhax.sometgirl.online

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
