title: Humhax
description: Documenting the Humax 2Tune PVR.
theme: just-the-docs

url: https://humhax.sometgirl.online

aux_links:
  GitHub: https://github.com/sometgirldotonline/humhax
markdown: kramdown

kramdown:
  input: GFM
  parse_block_html: true

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
